---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: airflow
  region: ap-south-1

managedNodeGroups:
  - name: workers
    instanceType: t2.micro
    privateNetworking: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: docker
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        autoScaler: true

